services:
  backend:
    build: backend
    networks:
      - shared

  frontend:
    build: frontend
    depends_on:
      - backend
    networks:
      - shared


networks:
  shared:
    driver: bridge  # Default (i.e., this line can be omitted without error).